### ISSUE TITLE
BetaLAN page

### ISSUE THREAD

**Issue by Blodroed** [betauia/betauia.net#43]
# Description
Adding a page which gives an overview of what BetaLAN is

# ToDo's

- [ ] Basic info with pictures
- [x] Tickets link
- [ ] Join Crew button (-> redirects to a crew form)
- [ ] Pictures from previous Lan-parties
